### ISSUE TITLE
bot not send massage of welcome and leave

### ISSUE THREAD

**Issue by SDelitegamer** [LegendaryEmoji/welcome-bot#4]

**Comment by SDelitegamer** [comment]
i have setup all things but the bot not send the massage

**Comment by royal-knight** [comment]
same

**Comment by LegendaryEmoji** [comment]
make sure intents are on

**Comment by LegendaryEmoji** [comment]
also i just updated bot, can you please download updated files

**Comment by Raposin** [comment]
the same thing happened to me

**Comment by Matteus130** [comment]
how Do i turn on intents

**Comment by Raposin** [comment]
lipi#6666 Send me a message, add me.

**Comment by LegendaryEmoji** [comment]
> how Do i turn on intents

[Click Here For Guide](https://github.com/LegendaryEmoji/random-guides/blob/main/Guides/discord-bot-intents.md)
